name: Build and Deploy

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 21.1.0

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: What İs My İp
        run: curl ifconfig.me
      - name: Build Application
        run: npm run build 
    #   - name: Run Application
    #     run: npm run start

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out # Change this if your export directory is different